root: true

extends:
  - '@comicrelief/eslint-config/mixins/base'
  - '@comicrelief/eslint-config/mixins/flowtype'
  - '@comicrelief/eslint-config/mixins/jsdoc'
  - '@comicrelief/eslint-config/mixins/sonarjs'
  - '@comicrelief/eslint-config/mixins/unicorn'

ignorePatterns:
  - node_modules
  - dist
  - coverage
