root: true

extends:
  - '@comicrelief/eslint-config/mixins/base'
  - '@comicrelief/eslint-config/mixins/ts'

ignorePatterns:
  - node_modules
  - dist
  - coverage
  - babel.config.js

rules:
  unicorn/prefer-node-protocol: off
  '@typescript-eslint/no-explicit-any': off
