name: git-checks

on: [push]

jobs:
  check-fixup-commits:
    name: Check for fixup commits
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Block Merge with fixup commit
      uses: 13rac1/block-fixup-merge-action@v1.1.1
