name: PR checks

on: pull_request

permissions:
  pull-requests: read

jobs:
  semantic-pr:
    # See https://github.com/amannn/action-semantic-pull-request
    name: Semantic pull request
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
